services:
  - type: web
    name: task-manager-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanager
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: taskmanager-redis
          property: connectionString
    databases:
      - name: taskmanager
        databaseName: taskmanager
        user: taskmanager
    redis:
      - name: taskmanager-redis 