services:
  - type: web
    name: task-manager-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    port: 3000
    healthCheckPath: /documentation
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanager
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: taskmanager-redis
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: POSTGRES_HOST
        fromDatabase:
          name: taskmanager
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: taskmanager
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: taskmanager
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: taskmanager
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: taskmanager
          property: database
    databases:
      - name: taskmanager
        databaseName: taskmanager
        user: taskmanager
        plan: free
    redis:
      - name: taskmanager-redis
        plan: free 